---
  - name: start NGINX
    service:
      name: nginx
      state: started
      enabled: yes
  - name: change php8.0-fpm to listen via port (removes hardcoded sock location)
    lineinfile:
      path: /etc/php8.0/fpm/pool.d/www.conf
      search_string: 'listen = /run/php/php8.0-fpm.sock'
      line: 'listen = 127.0.0.1:9000'

  - name: start PHP for Debian based OS
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    service:
      name: php8.0-fpm
      state: started
      enabled: yes

  - name: start PHP for CentOS based OS
    when: (ansible_distribution == "EL" or ansible_distribution == "CentOS")
    service:
      name: php-fpm
      state: started
      enabled: yes
