---

  - name: add ondrej's php ppa
    apt_repository:
      repo: 'ppa:ondrej/php'
      state: present
      update_cache: True


  - name: update cache
    apt: update_cache=yes
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: update system
    apt: upgrade=dist
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
