---

  - name: install packages
    apt:
      name:
        - 'nginx'
        - 'php'
        - 'php-mysql'
        - 'php-fpm'
        - 'php-cli'
        - 'php-gd'
        - 'php-json'
        - 'php-mbstring'
        - 'php-readline'
        - 'php-xml'
        - 'php-zip'
        - 'python3-pip'
        - 'mysql-server'
        - 'mysql-client'
        - 'libmysqlclient-dev'
        - 'python3-mysqldb'
        - 'unzip'
        - 'ufw'

      state: present

    register: task_result
    until: task_result is success
    retries: 10
    delay: 2


  - name: install certbot
    when: (leEmail is defined)
    apt:
      name: certbot
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
