---

  - name: start Mariadb
    when: (ansible_os_family == "Redhat")
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: start MySQL
    when: (ansible_os_family == "Debian")
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Make sure a database with the same name doesn't already exist.
    community.mysql.mysql_info:
      filter:
      - databases
      return_empty_dbs: yes
    register: dbList

  - name: fail if database with same name already exists
    fail:
      msg: "Database with this name already exists! will overwrite and cause problems with whatever is in the database. Change domainShort to something else to resolve"
    when: item in dbList.databases
    with_items:
      - "{{ domainShort }}"

  - name: Create a new database if a database by the same name doesn't already exist
    mysql_db:
      name: "{{ domainShort }}"
      login_user: "{{ mysqluser }}"
      login_password: "{{ mysqlpassword }}"
      state: present


  - name: Create a new user
    mysql_user:
      name: "{{ domainShort }}"
      password: "{{ db_password }}"
      login_user: "{{ mysqluser }}"
      login_password: "{{ mysqlpassword }}"
      priv: '*.*:All'
      state: present
