---

  - name: start Mariadb
    when: (ansible_distribution == "EL" or ansible_distribution == "CentOS")
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: start MySQL
    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Make sure a database with the same name doesn't already exist.
    mysql_db:
      name: "{{ domain short }}"
      state: absent
    register: databaseExist
    fail:
      msg: "Database with this name already exists! will overwrite or cause problems with whatever is in the database"
    when: databaseExist.stat.exists

  - name: Create a new database if a database by the same name doesn't already exist
    mysql_db:
      name: "{{ domainShort }}"
      login_user: "{{ mysqluser }}"
      login_password: "{{ mysqlpassword }}"
      state: present
      when: not databaseExist.state.exists

  - name: Create a new user
    mysql_user:
      name: "{{ domainShort }}"
      password: "{{ db_password }}"
      login_user: "{{ mysqluser }}"
      login_password: "{{ mysqlpassword }}"
      priv: '*.*:All'
      state: present
